### ISSUE TITLE
Internal Error: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by raynerluo** [gogf/gf#1770] opened 2022-04-18 16:43 UTC
### 1. What version of `Go` and system type/arch are you using?

go version go1.18 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.16.7

### 3. Can this issue be re-produced with the latest release?
v2.0.6 no longer has this problem

### 4. What did you do?

```go
package main

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
)

func main() {

	g.Server().BindHandler("/", func(r *ghttp.Request) {
		formMap := r.GetMap()
		r.Response.WriteJsonExit(formMap)
	})

	g.Server().SetPort(9090)
	g.Server().Run()
}
```

### 5. What did you expect to see?
```
command：curl -d '{"id":1}' http://127.0.0.1:9090      
response： {"id":1}
```

### 6. What did you see instead?
```
command：
         curl -d '{"id":1}' http://127.0.0.1:9090 
response：
        Internal Error: runtime error: slice bounds out of range [:8] with capacity
server log：
        2022-04-19 00:24:43.455 500 "POST http 127.0.0.1:9090 / HTTP/1.1" 0.000, 127.0.0.1, "", "curl/7.79.1"
        Stack:
       1. Internal Error: runtime error: slice bounds out of range [:8] with capacity 0
       1).  main.main.func1
        /Users/rayner/Apps/test/main.go:18
       2. runtime error: slice bounds out of range [:8] with capacity 0
```

**Comment by gqcn** [comment] 2022-04-19 08:30
@raynerluo This is a serious issue in `v1` version of `goframe`, which was caused by usage package `unsafe`. It is resolved in `v2` version of `goframe`. You'd better consider upgrading.

**Closed by gqcn** 2022-04-19 08:30 UTC
